title: Monadic Nomads
description: >-
  Random thoughts on current events, society and technology. Personal opinion.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://monads-nomads.github.io"

# Build settings
# theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# If you want to link only specific pages in your header, use this and add the path to the pages
# in order as they should show up.
header_pages:
  - archive.html
  - about.md

minima:
  solarized-light	   Light variant of solarized color scheme.

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
